server:
  port: 0

spring:
  profiles:
    include: token
  h2:
    console:
      enabled: true
      path: /h2-console



---

spring:
  profiles: local


logging:
  level:
    org.hibernate.SQL: DEBUG